name: Validate library

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ghcr.io/pgmq/pg17-pgmq:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.3
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Initialize database
        run: psql postgres://postgres:postgres@127.0.0.1:5432/postgres -c 'CREATE EXTENSION pgmq;'

      - name: Run tests
        run: deno test -A
        env:
          DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/postgres"
